### ISSUE TITLE
Warning and errrors while building angular ssr app

### ISSUE THREAD

**Issue by Stopy** [instana/nodejs#365] opened 2021-07-20 13:32 UTC
**Environment**
CentOS Linux release 7.8.2003 (Core)
node.js v12.11.1
yarn v1.22.5

**Dependencies:**
"@angular/core": "~9.1.7",
"express": "^4.15.2",
"@nguniversal/express-engine": "^9.1.0",
"@instana/collector": "^1.129.0"

**Problem:**
After adding Instana, as shown below, build ends with warnings, errors. So build doesn't work.

```
// Instana
// tslint:disable-next-line
import instana from '@instana/collector';
// You need to call the exported function *immediately*, before importing anything else.
instana();

// tslint:disable-next-line
import { APP_BASE_HREF } from '@angular/common';
import { ngExpressEngine as engine } from '@nguniversal/express-engine';
import { REQUEST, RESPONSE } from '@nguniversal/express-engine/tokens';
import { NgExpressEngineDecorator } from '@spartacus/core';
import * as express from 'express';
import { existsSync, readFileSync } from 'fs';
import { createProxyMiddleware } from 'http-proxy-middleware';
import { createServer } from 'https';
import { join } from 'path';
import 'zone.js/dist/zone-node';

import { AppServerModule } from './src/main.server';

const ngExpressEngine = NgExpressEngineDecorator.get(engine);

// The Express app is exported so that it can be used by serverless Functions.
export function app() {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/storefront/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html'))
  ...
```

**End of the build log:**
```
Hash: 5272a7f256b5360005e8
Time: 112384ms
Built at: 2021-07-20 16:09:02
  Asset      Size  Chunks                    Chunk Names
main.js  11.5 MiB       0  [emitted]  [big]  main
Entrypoint main [big] = main.js
chunk    {0} main.js (main) 19.5 MiB [entry] [rendered]

WARNING in ./node_modules/@instana/collector/src/index.js 45:52-103
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/@instana/shared-metrics/src/http.js 22:25-48
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/@instana/core/src/tracing/index.js 156:51-78
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/@instana/core/src/metrics/index.js 47:25-64
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/@instana/shared-metrics/src/util/nativeModuleRetry.js 95:27-49
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/@instana/shared-metrics/src/util/nativeModuleRetry.js 294:29-67
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/@instana/autoprofile/lib/auto_profiler.js 9:12-61
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/@instana/autoprofile/lib/auto_profiler.js 91:19-37
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/dtrace-provider/dtrace-provider.js
Module not found: Error: Can't resolve './src/build' in '/home/aa.udalov/git/storefront/node_modules/dtrace-provider'

WARNING in ./node_modules/node-gyp/lib/Find-VisualStudio.cs 9:6
Module parse failed: Unexpected token (9:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // This script needs to be compatible with PowerShell v2 to run on Windows 2008R2 and Windows 7.
| 
> using System;
| using System.Text;
| using System.Runtime.InteropServices;
Done in 360.68s.
```

**Comment by willianpc** [comment] 2021-07-21 10:10
Hi @Stopy thanks for reporting this issue.
Based on my initial investigation, this seems to be related to the way the Webpack works.
It seems not to like dynamic imports, eg: `this.addon = require(addonPath);` extracted from `WARNING in ./node_modules/@instana/autoprofile/lib/auto_profiler.js 91:19-37`.

I took a quick look at this post where they discuss about a similar issue: https://stackoverflow.com/questions/42908116/webpack-critical-dependency-the-request-of-a-dependency-is-an-expression

However I still didn't try it myself.
Could you maybe take a look at is as well? In the meantime, I will try to reproduce the issue with a small app that is bundled with Webpack.

- Willian C.

**Comment by willianpc** [comment] 2021-07-22 11:37
Hi @Stopy ,

After some more investigation and some chat with one of the collaborators of Webpack, the recommendation would be to keep `node_modules` out of your bundle.
This will of course require you to add the production dependencies of your application in a package.json in the same directory as your - already bundled - project.

Basically, our API relies on native modules that are compiled through node-gyp, which causes some problems for Webpack, like the error you are facing.

I invite you to check the entire discussion here: https://github.com/webpack/webpack/discussions/13833
Please, note that this issue is not caused directly by our API, but it comes from another library that we depend on.

If you have further questions, feel free to reply to this thread. Otherwise I believe that the issue can be closed.

Cheers, 
- Willian C.

**Comment by Stopy** [comment] 2021-07-22 14:51
Hi @willianpc,
Thanks for your time.
I haven't got what you mean when you say "keep node_modules out of your bundle". We are using Angular, so we don't have a possibility to deeply change webpack config. Also our back and front code are connected to each other quite hard, cuz of SSR and so on.

**Comment by willianpc** [comment] 2021-07-23 06:52
Hi @Stopy ,
I understand.

Have you had a chance to check the discussion I had with the collaborator of Webpack? I think you can find all the details you are looking for in there.
But the important bit to clarify your question is this:

1. Bundle the application without node_modules dependencies by using node-externals. This prevents Webpack from bundling them and keep a proper require('module') in place
2. Ship the bundle with package.json / package-lock.json /etc
3. During deployment process, run npm i --production or one of the similar options in order to get all the external dependencies properly built and to be require by the bundle

This blog post can also be helpful for you: https://archive.jlongster.com/Backend-Apps-with-Webpack--Part-I
One idea that I would try is to keep all externals (node_modules) in the build except for the node-gyp one. Then you follow the 3 steps mentioned above, but only for the node-gyp dependency.
You can use https://www.npmjs.com/package/webpack-node-externals as recommended by Alexander (the Webpack collaborator) and use the options to filter what should or should not be in the bundle.

If this doesn't help, then I think that pinging the Webpack team is the best approach.

Hope this helps!
- Willian

**Comment by willianpc** [comment] 2021-08-03 12:13
Hi @Stopy ,
I will close this issue as we explored all possible current solutions around bundling application with the Instana tracer.
Just as a last source of information, we have a documentation about this very same topic and directions on how to deal with the bundling, which is pretty much what we already discussed. But for a more formal explanation, please refer to : https://www.instana.com/docs/ecosystem/node-js/installation/#bundlers-webpack-and-similar

Best,
 - Willian

**Comment by basti1302** [comment] 2021-08-03 12:13
Please also see our documentation here: https://www.instana.com/docs/ecosystem/node-js/installation#bundlers-webpack-and-similar

Key points:

> The preferred installation method when you pre-process your Node.js server application with a bundler like Webpack or Rollup is described in [Installation Without Modifying the Source Code](https://www.instana.com/docs/ecosystem/node-js/installation#installation-without-modifying-the-source-code).

and

> In case you are using Angular CLI, in particular with [Angular Universal/SSR](https://angular.io/guide/universal), you should add "externalDependencies": ["@instana/collector"] (and possibly other libraries that @instana/collector instruments) to your angular.json file to exclude it/them from bundling (see [here](https://github.com/angular/angular-cli/blob/b1a5f49540f6cc2b477ec1333327238d07a766e4/packages/angular/cli/lib/config/schema.json#L1912)).

**Closed by willianpc** 2021-08-03 12:13 UTC

**Comment by basti1302** [comment] 2021-08-03 12:14
Oof, Willian beat me by a few seconds :D

**Comment by Stopy** [comment] 2021-08-04 22:49
Thanks you guys so much, works great. I just needed to not edit my source code and follow these steps https://github.com/instana/nodejs/issues/365#issuecomment-891797356
