### ISSUE TITLE
[Bug]:  minimatch.js needs to be updated to >3.0.4

### ISSUE THREAD

**Issue by spraguejdev** [instana/nodejs#634] opened 2022-10-06 19:56 UTC
### Problem Description

I'm using @instana/collector@2.10.0

minimatch minimatch.js braceExpand() Function Improper Regular Expression DoS. mini match contains a flaw in the braceExpand() function in minimatch.js that is triggered as an improper regular expression is used to match patterns for brace expansion. This may allow a context-dependent attacker to hang or slow down a Node process using the library.

https://huntr.dev/bounties/e4e1393c-d590-4492-9f43-8be3f3321629/https://github.com/isaacs/minimatch/commit/a8763f4388e51956be62dc6025cec1126beeb5e6

### Node.js Version

16

### package.json

```shell
N/A
```

### package-lock.json

```shell
N/A
```

**Comment by kirrg001** [comment] 2022-10-07 08:35
Hi there!

We are not using minimatch <= 3.0.4 in production mode. 

    mkdir instana-installation
    cd instana-installation
    npm init
    npm i @instana/collector@latest
    npm ls minimatch

```
└─┬ @instana/collector@2.10.0
  ├─┬ @instana/shared-metrics@2.10.0
  │ └─┬ recursive-copy@2.0.14
  │   ├─┬ maximatch@0.1.0
  │   │ └── minimatch@3.1.2
  │   └─┬ rimraf@2.7.1
  │     └─┬ glob@7.2.3
  │       └── minimatch@3.1.2 deduped
  └─┬ bunyan@1.8.15
    └─┬ mv@2.1.1
      └─┬ rimraf@2.4.5
        └─┬ glob@6.0.4
          └── minimatch@3.1.2 deduped
```

I am wondering if your problem is caused by a different package in your dependency tree?
Alternatively it is worth checking if your subdependencies are on the latest. You can use [npm update](https://docs.npmjs.com/cli/v8/commands/npm-update).

**Comment by basti1302** [comment] 2022-10-11 07:58
Closing this. It is a low severity CVE in a version of a package that we do not even use in our production code. Please refrain from creating issues like this in the future, thanks.

**Closed by basti1302** 2022-10-11 07:58 UTC
Labels: discussion
