### ISSUE TITLE
[Bug]: Module iitm-loader.mjs not found

### ISSUE THREAD

**Issue by mazzomix** [instana/nodejs#1200] opened 2024-06-26 12:08 UTC
### Problem Description

Hello

With the latest release (3.14.0) we get the following error in the container build process
<img width="1424" alt="image" src="https://github.com/instana/nodejs/assets/42975441/3e855bdd-740e-44ac-897b-4647182a66d3">

We used the snippet as described [here](https://www.ibm.com/docs/en/instana-observability/current?topic=agents-aws-fargate#ecmascript-modules)

Version 3.13.0 works.

Please let me know if the package.json should have any impact on finding a solution then I will deliver it subsequently.

### Node.js Version

18.18.2

### package.json

```shell
Should not be relevant
```

### package-lock.json

```shell
Should not be relevant
```

**Comment by aryamohanan** [comment] 2024-06-26 12:16
Thank you for the report. We will take a look asap.

**Comment by aryamohanan** [comment] 2024-06-26 12:27
I have merged a fix this issue

**Comment by aryamohanan** [comment] 2024-06-26 16:21
The fix has been released at the latest [release](https://github.com/instana/nodejs/releases/tag/v3.14.1) .

**Comment by mazzomix** [comment] 2024-06-27 08:44
Hi @aryamohanan 
Building the container works fine now, unfortunately running the container exits with code 13.

**Comment by aryamohanan** [comment] 2024-06-27 13:09
Could you kindly provide the container logs if possible? Additionally, could you specify the command you are using in the Dockerfile? I am unable to reproduce the issue. Thank you in advance.

**Comment by mazzomix** [comment] 2024-06-27 15:43
[log.txt](https://github.com/user-attachments/files/16017598/log.txt)
Thats the section where I think it happens, put verbose output on. Its not happening with version 3.13.0

**Comment by aryamohanan** [comment] 2024-06-27 18:23
@mazzomix  Thank you for the logs; I didn't find any errors related to Instana. Could you please provide a minimal example or steps to reproduce the issue? Also, can you confirm that no other updates were made besides updating the version of @instana/collector?

**Comment by mazzomix** [comment] 2024-06-28 07:07
Ok the reason I thought it is related is because it works with just changing the version of the collector to 3.13. But I will investigate a little further and try to create a reproducible example.

**Comment by aryamohanan** [comment] 2024-07-02 11:53
@mazzomix, I'm currently investigating the issue from our side. Have you had a chance to create a reproducible example?

**Comment by mazzomix** [comment] 2024-07-02 15:29
@aryamohanan Unfortunately I could not make it crash with some minimal reconstruction of the container until now. I guess it is some dependency I will try to put them in one after another

**Comment by aryamohanan** [comment] 2024-07-04 15:14
@mazzomix Thanks for the response.I will close the issue. Please feel free to reopen it if you continue to experience any problems. Thank you.

**Closed by aryamohanan** 2024-07-04 15:14 UTC
Labels: bug
