### ISSUE TITLE
[Bug]: Instana instrumentation fails in applications using bull repeatable jobs

### ISSUE THREAD

**Issue by jonathansamines** [instana/nodejs#410] opened 2021-10-28 23:33 UTC
### Problem Description

When the instana collector is loaded in an application using bull repeatable jobs, then the instrumentation fails and makes the application fail with the following error:

```bash
Cannot read property 'opts' of null
    TypeError: Cannot read property 'opts' of null
        at instrumentedProcessJob (/opt/xoom/apps/txm/node_modules/@instana/core/src/tracing/instrumentation/messaging/bull.js:188:23)
        at Queue.processJob (/opt/xoom/apps/txm/node_modules/@instana/core/src/tracing/instrumentation/messaging/bull.js:178:14)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I looked a bit into this issue and seems to be caused by the fact that the `job` argument is optional for the [Queue.prototype.processJob](https://github.com/OptimalBits/bull/blob/8968e7227d1b3216e92e84e125adced1c7adfce1/lib/queue.js#L1057) method which instana instruments considering that fact:

https://github.com/instana/nodejs/blob/2a2aaf4aa675a10ba0534c50e9bd2c34ab104d78/packages/core/src/tracing/instrumentation/messaging/bull.js#L187-L194

However as you can see, the instrumentation unsafely access the optional `job` argument on L188-L189 before the optional argument check.

### Short, Self Contained Example

Not at this time, if necessary I can try to isolate the issue.

### Node.js Version

14.17.5

### package.json

```shell
-
```

### package-lock.json

```shell
-
```

**Comment by willianpc** [comment] 2021-11-03 09:04
PR with the fix: https://github.com/instana/nodejs/pull/412

**Comment by willianpc** [comment] 2021-11-11 09:57
I am closing the issue as the problem is resolved.
Feel free to reopen it if the problem persists.

- Willian

**Closed by willianpc** 2021-11-11 09:57 UTC
Labels: bug

**Comment by jonathansamines** [comment] 2021-12-02 16:02
Hey @willianpc, sorry for the late response. I can confirm that as of 1.137.0, instrumentation works properly for bull repeatable jobs.
