### ISSUE TITLE
[Bug]: Incorrect process identification when pino v7+ transports are used

### ISSUE THREAD

**Issue by jonathansamines** [instana/nodejs#500] opened 2022-03-09 23:17 UTC
### Problem Description

When the `@instana/collector` is loaded into a Node.js application, but that application also uses pino v7+ [transports](https://getpino.io/#/docs/transports), then the Node.js process is sometimes identified as `thread-stream` instead of using the actual application name. The reproduction also includes a scenario where the same transport is used as a pino [destination](https://getpino.io/#/docs/api?id=destination) (omit the `MODE` env variable), in such cases the process is correctly identified.

**Note:** I cannot reliable reproduce the problem, sometimes the process is correctly identified even when pino transports are used. The problem may have something to do with the fact that pino transports work by using worker threads, but that is as far as my knowledge of the problem goes.

### Short, Self Contained Example

See [reproduction repository](https://github.com/jonathansamines/instana-pino-transport)

### Node.js Version

See reproduction

### package.json

```shell
See reproduction
```

### package-lock.json

```shell
See reproduction
```

**Comment by kirrg001** [comment] 2022-03-10 09:58
Hi there!

Thanks for providing the reproduction repository :) 

I cannot reproduce the problem you are running into 🤔 

In your example you are using [`logger.info`](https://github.com/jonathansamines/instana-pino-transport/blob/main/index.js#L18).

Instana collector does not trace info logs, only warn, error or fatal level.

If you change this line to `logger.warn` or `logger.error` it should report the spans correctly.

I tested your example and it's working for me fine and shows: **instana-pino-transport v1.0.0**

**Comment by jonathansamines** [comment] 2022-03-10 16:05
> Instana collector does not trace info logs, only warn, error or fatal level.

Yeah, logging collection seems to be working fine, it at the process identification where I am running into the problem described, but again I cannot reliably reproduce it either.

Thanks for checking.

**Comment by jonathansamines** [comment] 2022-03-16 17:36
Thank you.

**Comment by basti1302** [comment] 2022-03-29 13:42
We were now able to reproduce this. This only happens when the process is instrumented via `NODE_OPTIONS="--require @instana/collector/src/immediate` or via the Kubernetes autotrace webhook (which uses the same mechanism behind the scenes). Worker threads inherit the env, including NODE_OPTIONS which introduced some unexpected behavior, including the symptoms around changing the name you noticed.

A fix (#517) will be included in one of the next few releases.

**Comment by jonathansamines** [comment] 2022-03-29 16:48
Awesome, thank you.

**Closed** 2022-04-01 07:22 UTC
Labels: discussion

**Comment by kirrg001** [comment] 2022-04-01 08:52
The fix got merged and will be released next week 👍
